### ISSUE TITLE
Thank you very much for your module

### ISSUE THREAD

**Issue by javifly** [AlessandroTischer/tuya_climate_mult_edit#2]
Thank you very much for your module, it was great to find it and solve my problem. I have created a small manual to help anyone who wants to install it:

https://github.com/home-assistant/core/issues/104164#issuecomment-1826135261

If you want to improve the module cover and add this manual you are free to do so. I tell you this because there are other much worse modules that have better cover and are more used. https://github.com/midstar/homeassistant_tuya_with_bht-002_support

**Comment by AlessandroTischer** [comment]
Thank you for the effort. Before doing so, I should update the repo based on the newer Tuya core sources, since it creates an error notification on boot...

**Comment by javifly** [comment]
yes it is true, there is a notification of the start-up error. but I think your project has a lot of future and has not had the diffusion it deserves. There are many people with this problem and your project is the best solution without a doubt, if you want to dedicate a couple of hours of work it will be great for thousands of users.

I have found many people with the same problem:
https://github.com/home-assistant/core/issues/72703
https://github.com/home-assistant/core/issues/73612

There is even a module they have created to solve this: https://github.com/midstar/homeassistant_tuya_with_bht-002_support
But in my case I have used your method, is much simpler and more convenient.

**Comment by javifly** [comment]
I've been working with this integration for a week now and it's working perfectly! If you have the problem that your MOES thermostat does not dial correctly, here is a simple solution without losing the official integration. Because you can have both at the same time.

**Comment by javifly** [comment]
Hi AlessandroTischer,

This still works perfectly. The only drawback as you say is that at startup of the HA it gives a notification message, but only at startup, after that it never comes up again.

Do you plan to update the repository?

**Comment by javifly** [comment]
Do you plan to give an update to the repository? or are you going to leave it like that...?

**Comment by AlessandroTischer** [comment]
> Do you plan to give an update to the repository? or are you going to leave it like that...?

If I find some time during the winter holidays I'll try to fix it, but I won't make any promises

**Comment by javifly** [comment]
Thank you very much! Many users would be very grateful for the continuation and updating of the project.

**Comment by javifly** [comment]
I have heard that in the next update of homeassistant the official tuya app will stop working because from now on there is a new pairing system with the tuya app. You no longer have to enter the developers website, or create a project or anything ....

**Comment by javifly** [comment]
With the update 2024.2.0 the official integration of yours has changed the way of connection to yours servers. And as soon as this version is installed, the connection to your integration is lost. But, good news, those of you who have the modified version for the thermostat continues to work normally: https://github.com/AlessandroTischer/tuya_climate_mult_edit

**Comment by AlessandroTischer** [comment]
I updated the component from 2024.2 sources!
In order to get everything working, just reconfigure the integration and follow the config flow.

**Comment by javifly** [comment]
The integration works perfectly as of 02/25/2024

Today I tested the new integration with the new login method. The new login system works perfectly, although when the link is done correctly I got a strange success message.

![image](https://github.com/AlessandroTischer/tuya_climate_mult_edit/assets/38109926/0d0f5ec2-2353-4755-82ad-52c2f38a12d1)


my MOES thermostat works perfectly and keeping the names and rules in working order.

**Comment by AlessandroTischer** [comment]
> The integration works perfectly as of 02/25/2024 @AlexTischer 
> 
> Today I tested the new integration with the new login method. The new login system works perfectly, although when the link is done correctly I got a strange success message.
> 
> ![image](https://github.com/AlessandroTischer/tuya_climate_mult_edit/assets/38109926/0d0f5ec2-2353-4755-82ad-52c2f38a12d1)
> 
> 
> my MOES thermostat works perfectly and keeping the names and rules in working order.
> 
> 
> 

I honestly have no idea about that. If there is no error after the setup, I wouldn't worry

**Comment by javifly** [comment]
there is no error, once I accepted that window everything works fine.
